= File Access Policy
The File Access Policy Daemon (fapolicyd) controls the execution of applications based on a user-defined policy, and is one of the most effective ways to mitigate the risk of untrusted and possibly malicious applications on the system.

== Step 1. Installing the File Access Policy Daemon
First, install the fapolicyd package on your Red Hat Enterprise Linux system.

[source,bash,role="execute",subs=attributes+]
----
sudo dnf install -y fapolicyd
----

Next, inspect the fapolicyd configuration that has been created.

[source,bash,role="execute",subs=attributes+]
----
sudo cat /etc/fapolicyd/fapolicyd.conf
----

We can see a couple of things have been configured for us by default:
* The daemon is configured in enforcing mode `permissive = 0`, meaning all unauthorized processed will be blocked. We can optionally configure the daemon for permissive mode and to log unauthorized processes, rather than block them.
* A new user has been created on the system for the daemon `uid = fapolicyd`
* The default sources of trust are the RPM database and a file-backed trust database. This means that any packages installed into the RPM database will be trusted by default. In addition, a file is configured at `/etc/fapolicyd/fapolicyd.trust` which can be used for third-party binaries and other applications not installed into the RPM database.
* There is currently no integrity checking configured `integrity = none`

== Step 2. Verify the File Access Policy
Now that we've seen how the daemon is configured, let's see it in action.

As the lab-user, let's pull down a new application from an internet source, `cowsay`. There is nothing inherently malicious about this binary, though it provides a good example for our application control workflow.

[source,bash,role="execute",subs=attributes+]
----
curl -L -O https://github.com/Code-Hex/Neo-cowsay/releases/download/v2.0.4/cowsay_2.0.4_Linux_x86_64.tar.gz
----

Now, extract `cowsay` into the user's home directory.

[source,bash,role="execute",subs=attributes+]
----
tar xsf cowsay_2.0.4_Linux_x86_64.tar.gz
----

You should have no problems executing the `cowsay` binary:

[source,bash,role="execute",subs=attributes+]
----
./cowsay "mooooo"
----

Let's start up fapolicyd and see what happens:

[source,bash,role="execute",subs=attributes+]
----
sudo systemctl start fapolicyd
----

Now run the cowsay command again.

[source,bash,role="execute",subs=attributes+]
----
./cowsay "mooooo"
----

You'll obtain the following error.

....
[lab-user@rhel ~]$ ./cowsay "mooooo"
-bash: ./cowsay: Operation not permitted
[lab-user@rhel ~]$ 
....

Great! Because the `cowsay` binary isn't in the RPM database, or the file-backed trust database configured at `/etc/fapolicyd/fapolicyd.trust`, the execution is blocked.

== Step 3. Update the File Access Policy

What if we know that the `cowsay` binary is trusted, and we want to allow it on the system? We have a couple of options:

* We could create a RPM spec file for the binary, build an RPM, sign it, and install it into the RPM database
* We can update the file-backed trust database

The second option seems better for this scenario - let's update the file-backed trust database. We can use the `fapolicyd-cli` to update the trust source:

[source,bash,role="execute",subs=attributes+]
----
sudo fapolicyd-cli --file add /home/lab-user/cowsay
----

If we take a look at the file `/etc/fapolicyd/fapolicyd.trust` we can see that changes that have been made:

[source,bash,role="execute",subs=attributes+]
----
sudo cat /etc/fapolicyd/fapolicyd.trust
----

* The full-path to the file is listed (`/home/lab-user/cowsay`)
* The size of the file has been calculated and added
* The SHA-256 hash for the file has been calculated and added
Remember that we have `integrity = none` in our fapolicyd config file? These last two attributes - size and the SHA-256 has - are used for integrity checking. We'll take a closer look at this in the next step of the lab.

Now you can update the daemon:

[source,bash,role="execute",subs=attributes+]
----
sudo fapolicyd-cli --update
----

Let's try the binary again:

[source,bash,role="execute",subs=attributes+]
----
./cowsay "mooooo"
----

Success! We've verified that fapolicyd can block unauthorized processes and applications on a system, and that we can manage exceptions for trusted applications.

== Step 4. Explore fapolicyd integrity

Let's take a quick look at fapolicyd and integrity. The `more` command is installed via the RPM database, so it's trusted to execute on the system:
[source,bash,role="execute",subs=attributes+]
----
sudo rpm -qf /bin/more
----

What if the more command was substituted out for something malicious? First, let's verify that fapolicyd is still running:

[source,bash,role="execute",subs=attributes+]
----
sudo systemctl status fapolicyd
----

If you have followed the steps above, you should see the following.

----
● fapolicyd.service - File Access Policy Daemon
     Loaded: loaded (/usr/lib/systemd/system/fapolicyd.service; disabled; preset: disabled)
     Active: active (running) since Thu 2025-05-01 00:06:46 UTC; 13min ago
       Docs: man:fapolicyd(8)
    Process: 41956 ExecStartPre=/usr/sbin/fagenrules (code=exited, status=0/SUCCESS)
    Process: 41980 ExecStart=/usr/sbin/fapolicyd (code=exited, status=0/SUCCESS)
   Main PID: 41981 (fapolicyd)
      Tasks: 4 (limit: 48028)
     Memory: 67.1M
        CPU: 3.616s
     CGroup: /system.slice/fapolicyd.service
             └─41981 /usr/sbin/fapolicyd

May 01 00:06:46 rhel.qmfql.internal fapolicyd[41981]: Loading trust data from rpmdb backend
May 01 00:06:47 rhel.qmfql.internal fapolicyd[41981]: Loading trust data from file backend
May 01 00:06:47 rhel.qmfql.internal fapolicyd[41981]: Starting to listen for events
May 01 00:06:58 rhel.qmfql.internal fapolicyd[41981]: It looks like there was an update of the system... >
May 01 00:06:58 rhel.qmfql.internal fapolicyd[41981]: Loading rpmdb backend
May 01 00:06:58 rhel.qmfql.internal fapolicyd[41981]: Updating trust database
May 01 00:06:58 rhel.qmfql.internal fapolicyd[41981]: Creating trust database
May 01 00:06:58 rhel.qmfql.internal fapolicyd[41981]: Loading trust data from rpmdb backend
May 01 00:06:58 rhel.qmfql.internal fapolicyd[41981]: Loading trust data from file backend
May 01 00:06:58 rhel.qmfql.internal fapolicyd[41981]: Updated
----

Now that we can on the 3rd line, that the status is "Active: active (running)", we can close out of the status.

[source,bash,role="execute",subs=attributes+]
----
:q
----

Now let's substitute the `more` command for the `cowsay` binary in our user's home directory:

[source,bash,role="execute",subs=attributes+]
----
sudo /bin/cp ./cowsay /bin/more
----

[source,bash,role="execute",subs=attributes+]
----
/bin/more "mooooo"
----

Hmmmm. So by default, fapolicyd doesn't check what the file looks like, only where it is executing from. This means that an attacker could potentially hijack the execution path of a trusted file, and execute malicious code on behalf of a user.


== Step 5. Configure fapolicyd integrity controls
To mitigate situations where a trusted binary is substituted, fapolicyd supports different types of file integrity:

* File-size checking - this is a very fast method of integrity checking, where fapolicyd verifies that the file is the correct size before allowing execution
* Comparing SHA-256 hashes - computing and checking SHA-256 checksums is more secure than file-size checking, but does have an impact on system performance.
* Integrity Measurement Architecture (IMA) subsystem - IMA can be used by fapolicyd to support file integrity checks.


For this scenario we're going to use SHA-256 hashes to verify file integrity. This provides a good balance between speed and security, and is simple to setup and maintain.

You can configure integrity in the `/etc/fapolicyd/fapolicyd.conf` file:

[source,bash,role="execute",subs=attributes+]
----
sudo sed -i 's/integrity.*/integrity = sha256/' /etc/fapolicyd/fapolicyd.conf
----
Restart the daemon:


[source,bash,role="execute",subs=attributes+]
----
sudo systemctl restart fapolicyd
----

We can now verify whether file integrity checking is performed:

[source,bash,role="execute",subs=attributes+]
----
/bin/more "mooooooo"
----


We don't want a rouge script or command to be able to act like a trusted tool, so we expect this to come back with a 'Operation not permitted' 

----
-bash: /bin/more: Operation not permitted
----

Success!

We've now mitigated the risk of an attacker hijacking a trusted binary on the system, by configuring fapolicyd integrity controls.



